<?php

declare(strict_types=1);

namespace TheOneDigi\TourSdk\Tests;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use TheOneDigi\TourSdk\Exception\ConfigurationException;
use TheOneDigi\TourSdk\PartnerSigner;

/**
 * Cross-language conformance: these vectors are generated by the TypeScript SDK
 * (tour-sdk/scripts/generate-hmac-fixtures.mjs). If this test fails, the PHP and
 * TS clients disagree and one of them will be rejected by travelo-api.
 *
 * Fixture copied from tour-sdk/fixtures/hmac/partner-hmac-fixtures.json — re-copy
 * when the signing scheme changes (PartnerAuthService in travelo-api).
 */
final class PartnerSignerTest extends TestCase
{
    /**
     * @return array<string, array{string, string, string, array<string, string>}>
     */
    public static function fixtureProvider(): array
    {
        $raw = file_get_contents(__DIR__ . '/fixtures/partner-hmac-fixtures.json');
        self::assertIsString($raw);

        /** @var array<string, mixed> $data */
        $data = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);

        $cases = [];
        foreach ($data['fixtures'] as $fixture) {
            $cases[$fixture['name']] = [
                (string) $data['client_id'],
                (string) $data['secret'],
                (string) $data['timestamp'],
                $fixture,
            ];
        }

        return $cases;
    }

    /**
     * @param array<string, string> $fixture
     */
    #[DataProvider('fixtureProvider')]
    public function test_produces_the_same_signature_as_the_typescript_sdk(
        string $clientId,
        string $secret,
        string $timestamp,
        array $fixture,
    ): void {
        $signer = new PartnerSigner($clientId, $secret);

        self::assertSame(
            $fixture['body_sha256'],
            hash('sha256', $fixture['body']),
            'Body hash drifted from the fixture.',
        );

        self::assertSame(
            $fixture['string_to_sign'],
            $signer->stringToSign($fixture['method'], $fixture['path'], $fixture['body'], $timestamp),
            'string-to-sign drifted from the fixture.',
        );

        self::assertSame(
            $fixture['signature'],
            $signer->sign($fixture['method'], $fixture['path'], $fixture['body'], $timestamp),
            'Signature drifted from the fixture.',
        );
    }

    public function test_algorithm_is_hmac_sha256(): void
    {
        $raw = file_get_contents(__DIR__ . '/fixtures/partner-hmac-fixtures.json');
        self::assertIsString($raw);

        $data = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);

        self::assertSame('HMAC-SHA256', $data['algorithm']);
    }

    public function test_normalize_path_drops_query_and_trims_slashes(): void
    {
        self::assertSame('api/partner/tours', PartnerSigner::normalizePath('/api/partner/tours/'));
        self::assertSame('api/partner/tours', PartnerSigner::normalizePath('api/partner/tours?take=5&page=2'));
        self::assertSame('api/partner/tours', PartnerSigner::normalizePath('/api/partner/tours?take=5'));
    }

    public function test_headers_carry_the_signature_triplet(): void
    {
        $signer = new PartnerSigner('cid', 'sec');

        $headers = $signer->headers('POST', 'api/partner/bookings', '{"a":1}', 1782276240);

        self::assertSame('cid', $headers[PartnerSigner::HEADER_CLIENT_ID]);
        self::assertSame('1782276240', $headers[PartnerSigner::HEADER_TIMESTAMP]);
        self::assertSame(
            $signer->sign('POST', 'api/partner/bookings', '{"a":1}', 1782276240),
            $headers[PartnerSigner::HEADER_SIGNATURE],
        );
    }

    public function test_headers_default_to_the_current_timestamp(): void
    {
        $headers = (new PartnerSigner('cid', 'sec'))->headers('GET', 'api/partner/tours', '');

        self::assertLessThanOrEqual(2, abs(time() - (int) $headers[PartnerSigner::HEADER_TIMESTAMP]));
    }

    public function test_rejects_empty_credentials(): void
    {
        $this->expectException(ConfigurationException::class);

        new PartnerSigner('cid', '');
    }
}
